server:
  port: 8761
  
eureka:  client:    register-with-eureka: false
    fetch-registry: false
  server:    wait-time-in-ms-when-sync-empty: 0  dashboard:    path: /bank/eureka  instance:    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 4