server:
  port: 9080
eureka:  client:
    service-url:      defaultZone: http://localhost:8761/eureka/
    healthcheck:      enabled: true
  instance:    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 4
spring:  application:    name: account-service